# Generated by Django 5.1.3 on 2024-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='catagory',
            field=models.CharField(choices=[('edu', 'education'), ('project', 'projects'), ('experience', 'experience')], default='edu', max_length=122),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/portfolio'),
        ),
    ]
